set dotenv-load := true # supply AWS_* variables for authentication.

kubeconfig_dir := justfile_directory() / ".kube"
talosconfig_dir := justfile_directory() / ".talos"

apply: && fetch-configs
    terraform init -input=false
    terraform apply -auto-approve -input=false

destroy:
    terraform init -input=false
    terraform destroy -auto-approve -input=false

fetch-configs:
    #!/usr/bin/env bash
    set -euo pipefail
    for cluster in $(jq -r '.k8s_clusters | keys[]' {{justfile_directory()}}/config.json); do
        {{just_executable()}} fetch-config "$cluster"
    done

fetch-config cluster:
    mkdir -p {{kubeconfig_dir}} {{talosconfig_dir}}
    terraform output -json kubeconfigs  | jq -er '."{{cluster}}"' > {{kubeconfig_dir}}/{{cluster}}.config
    terraform output -json talosconfigs | jq -er '."{{cluster}}"' > {{talosconfig_dir}}/{{cluster}}.config
