apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: chain-indexer
  namespace: ${APP_CHAIN_INDEXER_NAMESPACE}
spec:
  title: Chain Indexer
  instanceSelector:
    matchLabels:
      dashboards: grafana
  allowCrossNamespaceImport: true
