apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: indexer
  namespace: ${APP_CHAIN_INDEXER_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: indexer
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
    - port: metrics
      path: /metrics/runtime
      interval: 30s
