apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ${APP_CHAIN_INDEXER_SVC}
  namespace: ${APP_CHAIN_INDEXER_NAMESPACE}
spec:
  selector:
    matchLabels:
      app: ${APP_CHAIN_INDEXER_SVC}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
    - port: metrics
      path: /metrics/runtime
      interval: 30s
