apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-owner-vars
  namespace: flux-system
data:
  INDEXER_IMAGE_NAME: ghcr.io/tilakmaddy/my-envio-indexer:production
  # just backup-vars, in infra/production
  PG_BACKUP_DESTINATION: s3://oatlabs-backoffice-pg-backups-production/
  PG_BACKUP_REGION: us-west-2
