apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-owner-vars
  namespace: flux-system
data:
  CLUSTER_ZONE: us-west-2-aws-backoffice.oatlabs-production.oatmilk.work
  TXT_OWNER_ID: production-us-west-2-aws-backoffice-dataplane
  OP_VAULT: MyIndexer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-owner-vars
  namespace: flux-system
data:
  INDEXER_IMAGE_NAME: ghcr.io/tilakmaddy/my-envio-indexer:production
