apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-owner-vars
  namespace: flux-system
data:
  CLUSTER_ZONE: backoffice.oatlabs-local.oatmilk.work
  TXT_OWNER_ID: my-desk-kind-backoffice-dataplane
  OP_VAULT: MyIndexer
