apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
data:
  CLUSTER_ZONE: us-west-2-aws-marvel.oatlabs-production.oatmilk.work
  PG_INSTANCES: "3"
  PG_POOLER_INSTANCES: "3"
  PG_STORAGE: 1Gi
  PG_WAL_STORAGE: 1Gi

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/apps
  prune: true
  wait: true
  dependsOn:
    - name: bootstrap
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
