apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-owner-vars
  namespace: flux-system
data:
  CLUSTER_ZONE: us-west-2-aws-backoffice.oatlabs-staging.oatmilk.work
  TXT_OWNER_ID: staging-us-west-2-aws-backoffice-dataplane
  OP_VAULT: MyIndexer
