apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pg-backups
  namespace: flux-system
spec:
  interval: ${FLUX_INTERVAL}
  retryInterval: ${FLUX_RETRY_INTERVAL}
  timeout: ${FLUX_TIMEOUT}
  path: ./clusters/apps/chain-indexer/02-postgres/backups/${PG_BACKUPS_ENABLED}
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
      - kind: ConfigMap
        name: cluster-owner-vars
      - kind: ConfigMap
        name: chain-indexer-vars
