apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: chain-indexer
  namespace: chain-indexer
spec:
  instances: ${PG_INSTANCES}

  enableSuperuserAccess: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"

  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        effect: NoSchedule
        operator: Exists
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone
    podAntiAffinityType: required

  storage:
    size: ${PG_STORAGE}

  walStorage:
    size: ${PG_WAL_STORAGE}

  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: chain-indexer-postgresql-minimal-trixie
    major: 18

  bootstrap:
    initdb:
      dataChecksums: true
