apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${APP_CHAIN_INDEXER_PG_CLUSTER}
  namespace: ${APP_CHAIN_INDEXER_NAMESPACE}
spec:
  instances: ${PG_INSTANCES}

  enableSuperuserAccess: true
  superuserSecret:
    name: ${APP_CHAIN_INDEXER_PG_CLUSTER}-superuser-pass

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"

  affinity:
    nodeSelector:
      node-role.kubernetes.io/postgres: ""
    tolerations:
      - key: node-role.kubernetes.io/postgres
        effect: NoSchedule
        operator: Exists
    enablePodAntiAffinity: true
    topologyKey: topology.kubernetes.io/zone
    podAntiAffinityType: required

  storage:
    size: ${PG_STORAGE}

  walStorage:
    size: ${PG_WAL_STORAGE}

  postgresql:
    synchronous:
      method: any
      number: 1
      dataDurability: required

  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: ${APP_CHAIN_INDEXER_PG_CATALOG}
    major: ${APP_CHAIN_INDEXER_PG_MAJOR}

  bootstrap:
    initdb:
      dataChecksums: true
