apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: ${APP_CHAIN_INDEXER_PG_POOLER}
  namespace: ${APP_CHAIN_INDEXER_NAMESPACE}
spec:
  cluster:
    name: ${APP_CHAIN_INDEXER_PG_CLUSTER}

  instances: ${PG_POOLER_INSTANCES}
  type: rw

  monitoring:
    enablePodMonitor: true

  template:
    spec:
      containers:
        - name: pgbouncer
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
      topologySpreadConstraints:
        - topologyKey: topology.kubernetes.io/zone
          maxSkew: 1
          whenUnsatisfiable: DoNotSchedule
          nodeTaintsPolicy: Honor
          labelSelector:
            matchLabels:
              cnpg.io/poolerName: ${APP_CHAIN_INDEXER_PG_POOLER}

  pgbouncer:
    poolMode: session

    parameters:
      max_client_conn: "100"
      default_pool_size: "10"
      client_tls_sslmode: require
      server_tls_sslmode: verify-full

    clientTLSSecret:
      name: zone-certificate-tls
    serverCASecret:
      name: ${APP_CHAIN_INDEXER_PG_CLUSTER}-ca
