apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: ${APP_CHAIN_INDEXER_DB_NAME}
  namespace: ${APP_CHAIN_INDEXER_NAMESPACE}
spec:
  cluster:
    name: ${APP_CHAIN_INDEXER_PG_CLUSTER}
  name: ${APP_CHAIN_INDEXER_DB_NAME}
  owner: ${APP_CHAIN_INDEXER_DB_ROLE}
  databaseReclaimPolicy: delete

---
