apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-secret-vars
  namespace: flux-system
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cluster-secret-vars
    creationPolicy: Owner
  data:
    - secretKey: PG_BACKUP_DESTINATION
      remoteRef:
        key: ${OP_VAULT_PG_BACKUP_DESTINATION}
    - secretKey: PG_BACKUP_REGION
      remoteRef:
        key: ${OP_VAULT_PG_BACKUP_REGION}
    - secretKey: INDEXER_IMAGE_NAME
      remoteRef:
        key: ${OP_VAULT_INDEXER_IMAGE_NAME}
